# Generated by Django 3.2.7 on 2021-09-28 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('department', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='user/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Epic'), ('2', 'Bug'), ('3', 'Task'), ('4', 'Subtask'), ('5', 'Change'), ('6', 'IT help'), ('7', 'Incident'), ('8', 'New feature'), ('9', 'Problem'), ('10', 'Service request'), ('11', 'Support')], max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('1', 'Open'), ('2', 'In Progress'), ('3', 'Done'), ('4', 'To Do'), ('5', 'In Review'), ('6', 'Under review'), ('7', 'Approved'), ('8', 'Cancelled'), ('9', 'Rejected'), ('10', 'Draft'), ('11', 'Published'), ('12', 'Interviewing'), ('13', 'Accepted'), ('14', 'Purchased'), ('15', 'Requested')], default=1, max_length=10)),
                ('detail', models.TextField()),
                ('labels', models.TextField()),
                ('comments', models.TextField(default=[])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignee', models.ManyToManyField(related_name='ticket_to_assign', to=settings.AUTH_USER_MODEL)),
                ('attachments', models.ManyToManyField(to='app.Attachment')),
                ('category', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
