# Generated by Django 3.2.7 on 2021-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210928_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
