# Generated by Django 3.2.7 on 2021-09-28 12:29

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ticket_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Extraordinary'), (2, 'High'), (3, 'Moderate'), (4, 'Low')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('symbol', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('members', models.ManyToManyField(related_name='department_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
